### ISSUE TITLE
Crash on exit

### ISSUE THREAD

**Issue by smeyfroi** [roymacdonald/ofxLineaDeTiempo#15]
This is an odd one!

I'm still on a fairly out of date pre-v0.12 nightly: of_v20230215_osx_release

The issue is a nullptr crash on exit when I use the `Esc` key, but not when I use the menu->Quit option.

I don't see this behaviour in the sample apps but only my own (which started out like the 'basic' example and is now like the 'multi-window' example). So this is not going to be something easy to track down, but I'm raising the issue just to provide a bit of information in case there's an "obvious" thing somewhere. :-)

The crash is in ofx::PointerEventsManager, which I now realise is a copy of another library.

See screenshots for the details. After trying to exit the app with the `Esc` key, the PointerEventsManager->_windowEventMap ends up containing one element, a `pair` that contains only `{NULL, nullptr}`, which eventually leads to an illegal access later on.

Feel free to close this if it doesn't "mean" anything immediately. It's not blocking anything because the `Quit` menu option works fine.

![Screenshot 2023-09-24 at 15 55 47](https://github.com/roymacdonald/ofxLineaDeTiempo/assets/203996/78d00848-87c3-4ce8-bce4-6d4096875966)

![Screenshot 2023-09-24 at 15 55 17](https://github.com/roymacdonald/ofxLineaDeTiempo/assets/203996/69a0beee-4949-4ecf-a54e-74cf38eac651)

**Comment by roymacdonald** [comment]
can you share the code you are using?
are you using any static variables? This kind of errors in destructors is in many cases due to static dealocation order (which is the inverse order of creation of the static variables). 
I'll take a deeper look at your screen shots later.
Thanks for your feedbakc

**Comment by smeyfroi** [comment]
Sure, try this: I don't remember why I push everything to gitlab and I have no idea how gitlab works... I think all my stuff is public now though. 👍 https://gitlab.com/meyfroidt-art/assignment4

The static variables sounds like a very good guess though: see https://gitlab.com/meyfroidt-art/assignment4/-/blob/main/src/Layer.hpp?ref_type=heads#L31 and corresponding https://gitlab.com/meyfroidt-art/assignment4/-/blob/main/src/Layer.cpp?ref_type=heads#L11

Do you have a link to better code that manages per-class parameters for me to learn from (copy/paste 🤣)?

**Comment by smeyfroi** [comment]
Closing as the issue is my use of static variables

**Comment by roymacdonald** [comment]
thanks for closing. 
In general, be careful with static variables. Take a look at the "static initialization order fiasco". 
The general fix for such is that instead of making static class members you create functions (which can be static or not, class members or not) where you create the static object inside the function.

So for instance, instead of the following
` static ofParameter<int> maxFeatures;`
you would declare 
```
static ofParameter<int>& getMaxFeatures(){
static unique_ptr<ofParameter<int>> maxFeatures = make_unique<ofParameter<int>>("Max Features", 10, 10,100); // you can initialize it here.
return *maxFeatures.get();
}
```

Because of the static inside the function, that will only get called once, so you know it will be the same object each time you call this function. 
But then, the static object gets initialized only and if only you call this function (gets initialized the first time you call it).
So in this way you can control the order of initialization. Notice that the automatic order of deinitialization (destruction) is the inverse of initialization, so take into account this order if you have other object that might depend upon one of these upon their destruction. Which is what probably happens to you.
I hope this helps

**Comment by smeyfroi** [comment]
Ooooof OK, that helps a lot, thanks Roy! Looks like I've been too long out of C++... got some learning to do. 👍
